FROM ubuntu:latest

RUN <<EOF
apt update
apt install -y make cmake gcc
EOF

COPY client.c CMakeLists.txt /client/
COPY data /client/data
COPY networking /client/networking
WORKDIR /client

#RUN mkdir build && cd build && cmake ../ && make
#WORKDIR build

RUN gcc -o client client.c
RUN chmod +x client

ENV CLIENT_HOST=${CLIENT_HOST}
ENV CLIENT_PORT=${CLIENT_PORT}

ENTRYPOINT ./client "${CLIENT_HOST}" "${CLIENT_PORT}"
